version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepass
      POSTGRES_DB: moviedb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - movie-network

  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moviedb
      SPRING_DATASOURCE_USERNAME: movieuser
      SPRING_DATASOURCE_PASSWORD: moviepass
    networks:
      - movie-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9088:8080"
      - "50001:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - movie-network
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-new
    ports:
      - "9005:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - movie-network

volumes:
  db-data: {}
  jenkins-data: {}
  sonarqube-data: {}
  sonarqube-logs: {}
  sonarqube-extensions: {}

networks:
  movie-network:
    driver: bridge
